clear;
clc;
dufun=inline('(1-t*cos(u))*cot(u)');
tspan=[0,2];
u0=acos(1/2);
h=0.01;
tspan1=[0,3*h];
tspan1=[0,3*h];
%[t,u]=Kutta4(dufun,tspan1,u0,h)
[t,u1]=ODEAdams4pece(dufun,tspan,u0,h)
[t,u2]=Adams4(dufun,tspan,u0,h);
%[t3,u3]=Adams4_PC(dufun,tspan,u0,u(2),u(3),u(4),h)
%[t4,u4]=Adams4_Implict(dufun,tspan,u0,u(2),u(3),u(4),h);
uexact=acos(1./(t+1+exp(t)));
plot(t,u1,'*',t,u2,'*',t,uexact,'o');
legend('ODEAdams4pece','Adams4','exactsolu');
%plot(t1,u1,'*',t2,u2,'*',t3,u3,'*',t4,u4,'*',t2,uexact,'o');
%legend('ODEAdams4pece','Adams4','Adams4PC','Adams4Implict','exactsolu');
title('Adams4');
xlabel('t');ylabel('u');
figure(2)
err1=abs(uexact-u1)
err2=abs(uexact-u2)
%err3=abs(uexact-u3)
%err4=abs(uexact-u4);
%plot(t1,err1,'-')
%legend('err-ODEAdams4pece')
plot(t,err1,'-',t,err2,'r-');
legend('err-ODEAdams4pece','err-Adams4');
%plot(t1,err1,'-',t2,err2,'r-',t3,err3,'g-',t4,err4,'y-');
%legend('err-ODEAdams4pece','err-Adams4','err-Adams4PC','err-Adams4Implict')
xlabel('t');ylabel('error')
title('Error h=0.1');
figure(3)
err=err1-err2
plot(t,err);